# Generated by Django 2.1.5 on 2019-06-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190624_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail'),
        ),
    ]
