# Generated by Django 2.1.5 on 2019-06-24 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20190624_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='file_name',
            new_name='file',
        ),
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='type',
            field=models.CharField(choices=[('audio', 'AUDIO'), ('video', 'VIDEO')], default='audio', max_length=6),
        ),
    ]
