# Generated by Django 2.1.5 on 2019-06-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20190624_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='type',
        ),
    ]
